name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # GitHub 리포지토리에서 코드를 가져옵니다.

      # 'npm run build'와 'npm run export' 명령어를 프로젝트 루트 디렉토리에서 실행하도록 설정
      - run: npm run build && npm run export
        # Update or remove the following line based on the correct directory
        working-directory: ./Documents/follova  # Ensure this path exists

      - uses: FirebaseExtended/action-hosting-deploy@v0  # Firebase 배포를 위한 GitHub Action
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FOLLOVA }}"
          channelId: live  # 배포 채널
          projectId: follova  # Firebase 프로젝트 ID